// Svenska tätorter och orter baserat på SCB:s tätortsregister
export const SVENSKA_ORTER = [
  'Abisko', 'Aby', 'Agunnaryd', 'Alafors', 'Åled', 'Ålem', 'Åmål', 'Åmotfors', 'Åmsberg',
  'Åkersberga', 'Åkarp', 'Åkers Styckebruk', 'Åkersberga', 'Åled', 'Ålem', 'Åmål',
  'Ånge', 'Ängelholm', 'Åre', 'Åsarna', 'Åseda', 'Åstorp', 'Åtvidaberg',
  'Alingsås', 'Almedal', 'Alunda', 'Alvesta', 'Alvik', 'Ankarsrum', 'Arboga',
  'Arjeplog', 'Arkelstorp', 'Arlanda', 'Arvidsjaur', 'Arvika', 'Askersund',
  'Avesta', 'Bålsta', 'Båstad', 'Bengtsfors', 'Bergsjö', 'Bergsviken', 'Bergsåker',
  'Bettna', 'Billeberga', 'Billdal', 'Björbo', 'Björkö', 'Björklinge', 'Björksele',
  'Björneborg', 'Blentarp', 'Blomstermåla', 'Boden', 'Bollnäs', 'Bollebygd',
  'Borlänge', 'Borås', 'Borgholm', 'Botkyrka', 'Boxholm', 'Brastad', 'Bredaryd',
  'Bromma', 'Bräcke', 'Bräkne-Hoby', 'Burlöv', 'Burträsk', 'Bygdsiljum',
  'Charlottenberg', 'Dalby', 'Dals Långed', 'Dals-Ed', 'Danderyd', 'Degerfors',
  'Deje', 'Djurås', 'Dorotea', 'Edsbyn', 'Ekerö', 'Eksjö', 'Emmaboda',
  'Enköping', 'Eskilstuna', 'Eslöv', 'Eslov', 'Edsele', 'Edsbyn',
  'Fagersta', 'Falkenberg', 'Falköping', 'Falun', 'Färgelanda', 'Filipstad',
  'Finspång', 'Flen', 'Flyinge', 'Forshaga', 'Fors', 'Forssa',
  'Frösön', 'Gagnef', 'Gällivare', 'Gärsnäs', 'Gävle', 'Gnesta',
  'Gothenburg', 'Gotland', 'Grängesberg', 'Gränna', 'Grästorp', 'Grums',
  'Grundsund', 'Gullspång', 'Gunnilse', 'Gustavsberg', 'Göteborg',
  'Götene', 'Hagfors', 'Hallsberg', 'Hallstahammar', 'Hallstavik', 'Halmstad',
  'Hammerdal', 'Haninge', 'Haparanda', 'Härnösand', 'Härlöv', 'Hässleholm',
  'Hässleby', 'Hässlö', 'Helsingborg', 'Hedemora', 'Hofors', 'Hollviken',
  'Holmestrand', 'Holmsveden', 'Holo', 'Hovslätt', 'Huddinge', 'Hudiksvall',
  'Hultsfred', 'Hyltebruk', 'Hörby', 'Höganäs', 'Höllviken', 'Hönö',
  'Höör', 'Ingelstad', 'Järfälla', 'Järna', 'Järpen', 'Jokkmokk',
  'Jönköping', 'Kalix', 'Kalmar', 'Karlsborg', 'Karlshamn', 'Karlskoga',
  'Karlskrona', 'Karlstad', 'Kil', 'Kisa', 'Klippan', 'Knivsta',
  'Knutby', 'Kolbäck', 'Kopparberg', 'Korskrogen', 'Kramfors', 'Kristianstad',
  'Kristinehamn', 'Kungsbacka', 'Kungsör', 'Kungälv', 'Kvicksund', 'Köping',
  'Laholm', 'Landskrona', 'Leksand', 'Lerum', 'Lidingö', 'Lidköping',
  'Lindesberg', 'Lindome', 'Linköping', 'Ljungby', 'Ljusdal', 'Ljusne',
  'Lomma', 'Ludvika', 'Luleå', 'Lund', 'Lycksele', 'Lysekil',
  'Malmö', 'Malung', 'Mariestad', 'Markaryd', 'Märsta', 'Mjölby',
  'Molkom', 'Mora', 'Motala', 'Mullsjö', 'Munkedal', 'Mölndal',
  'Mönsterås', 'Mörbylånga', 'Nacka', 'Norberg', 'Norrköping', 'Norrtälje',
  'Norrtelje', 'Nybro', 'Nyköping', 'Nynäshamn', 'Nässjö', 'Ockelbo',
  'Olofström', 'Orsa', 'Orust', 'Oskarshamn', 'Oxelösund', 'Pajala',
  'Partille', 'Piteå', 'Rättvik', 'Ronneby', 'Sala', 'Salem',
  'Sand', 'Sandviken', 'Sigtuna', 'Simrishamn', 'Sjöbo', 'Skara',
  'Skellefteå', 'Skinnskatteberg', 'Skivarp', 'Skoghall', 'Skurup', 'Skövde',
  'Smedjebacken', 'Sollefteå', 'Sollentuna', 'Solna', 'Sorsele', 'Staffanstorp',
  'Stenungsund', 'Stockholm', 'Storuman', 'Strängnäs', 'Strömstad', 'Strömsund',
  'Stugun', 'Sundbyberg', 'Sundsvall', 'Sunne', 'Surahammar', 'Sveg',
  'Svenljunga', 'Säffle', 'Sälen', 'Säter', 'Sävsjö', 'Södertälje',
  'Söderhamn', 'Söderköping', 'Södertälje', 'Sölvesborg', 'Tanum', 'Tibro',
  'Tidaholm', 'Tierp', 'Timrå', 'Tingsryd', 'Tjörn', 'Tomelilla',
  'Torsby', 'Tranås', 'Tranemo', 'Trelleborg', 'Trollhättan', 'Trosa',
  'Tyresö', 'Täby', 'Töreboda', 'Uddevalla', 'Ulricehamn', 'Umeå',
  'Upplands Väsby', 'Upplands-Bro', 'Uppsala', 'Utansjö', 'Vadstena',
  'Vallentuna', 'Vänersborg', 'Vännäs', 'Varberg', 'Vargön', 'Vaxholm',
  'Vetlanda', 'Vilhelmina', 'Vimmerby', 'Vindeln', 'Visby', 'Vislanda',
  'Vittsjö', 'Värnamo', 'Västervik', 'Västerås', 'Växjö', 'Ystad',
  'Älmhult', 'Älvdalen', 'Älvkarleby', 'Älvsbyn', 'Åmotfors', 'Ängelholm',
  'Öckerö', 'Örebro', 'Örkelljunga', 'Örnsköldsvik', 'Östersund', 'Österåker',
  'Östhammar', 'Östra Göinge',
  // Stockholmsområdet
  'Botkyrka', 'Danderyd', 'Ekerö', 'Haninge', 'Huddinge', 'Järfälla',
  'Lidingö', 'Nacka', 'Norrtälje', 'Nynäshamn', 'Salem', 'Sigtuna',
  'Sollentuna', 'Solna', 'Sundbyberg', 'Södertälje', 'Tyresö', 'Täby',
  'Upplands Väsby', 'Upplands-Bro', 'Vallentuna', 'Vaxholm', 'Värmdö',
  'Österåker',
  // Mindre orter och samhällen
  'Abbekås', 'Adelsö', 'Agnesberg', 'Ahus', 'Åhus', 'Åkersberg',
  'Ala', 'Alberga', 'Alby', 'Alfta', 'Algutsrum', 'Alhamn',
  'Alingsås', 'Alnö', 'Alsen', 'Alsike', 'Alstad', 'Alsterbro',
  'Alstermo', 'Altersbruk', 'Altuna', 'Alunda', 'Alva', 'Ammarnäs',
  'Amot', 'Anderslov', 'Anderstorp', 'Aneby', 'Ange', 'Angered',
  'Annas', 'Annerstad', 'Anundsjö', 'Aplared', 'Arboga', 'Arbrå',
  'Ardala', 'Arkelstorp', 'Arnäsvall', 'Arnas', 'Arnö', 'Arontorp',
  'Arrie', 'Arsby', 'Artjärv', 'Aryd', 'Asarum', 'Åsarp',
  'Åsbyggeby', 'Åsby', 'Åseda', 'Åsen', 'Askeby', 'Askerön',
  'Åskloster', 'Åsle', 'Åsmundtorp', 'Åsnes', 'Åstol', 'Åstorp',
  'Asunden', 'Atran', 'Atvidaberg', 'Auneby', 'Augerum', 'Axamo',
  'Axvall', 'Balingslöv', 'Ballingslov', 'Balsta', 'Barseback',
  'Barsebacksstrand', 'Bastuträsk', 'Bavern', 'Bergby', 'Bergeforsen',
  'Berghem', 'Bergkvara', 'Bergnäset', 'Bergshamra', 'Bergsjö',
  'Bergvik', 'Billesholm', 'Bjärnum', 'Bjärred', 'Bjärtrå',
  'Bjästa', 'Bjorketorp', 'Björklinge', 'Björköby', 'Björna',
  'Björneborg', 'Björnlunda', 'Blidsberg', 'Blomstermåla', 'Blåsmark',
  'Blentarp', 'Bodafors', 'Boden', 'Bograngen', 'Bohus', 'Bohus-Björkö',
  'Boliden', 'Bollebygd', 'Bollstabruk', 'Bondstorp', 'Borgstena',
  'Borensberg', 'Borgsjö', 'Borgunda', 'Borlanda', 'Borrby', 'Bosarp',
  'Botildenborg', 'Brastad', 'Bredaryd', 'Bredäng', 'Bro', 'Broby',
  'Brokind', 'Bromölla', 'Brunn', 'Brunnby', 'Brunflo', 'Bruzaholm',
  'Brålanda', 'Bräkne-Hoby', 'Brännebrona', 'Budskär', 'Bullaren',
  'Bunkeflostrand', 'Bureå', 'Burgsvik', 'Burseryd', 'Bydalen',
  'Bygdsiljum', 'Byviken', 'Charlottenberg', 'Dala-Floda', 'Dalaro',
  'Dalby', 'Dals Rostock', 'Dalsjöfors', 'Dalstorp', 'Dalum',
  'Degeberga', 'Degerfors', 'Deje', 'Delsbo', 'Dingle', 'Djurö',
  'Djursholm', 'Dorotea', 'Ed', 'Edsbro', 'Edsbyn', 'Edsele',
  'Ekenässjön', 'Ekero', 'Ekshärad', 'Ektjärn', 'Enebyberg',
  'Enköping', 'Eriksberg', 'Eriksmåla', 'Eslöv', 'Espe',
  'Espelunda', 'Fagerberg', 'Fagerhult', 'Fagersta', 'Falkenberg',
  'Falköping', 'Falkoping', 'Farsta', 'Fegen', 'Fellingsbro',
  'Figeholm', 'Filipstad', 'Fiskeby', 'Fiskebäckskil', 'Fiskeby',
  'Fittja', 'Fjälkinge', 'Fjällbacka', 'Fjärdhundra', 'Fjelkinge',
  'Fliseryd', 'Floby', 'Floda', 'Floran', 'Flyinge', 'Folkaryd',
  'Forserum', 'Forshaga', 'Forshem', 'Forsnäs', 'Fosdalen',
  'Frändefors', 'Fristad', 'Fritsla', 'Fröjered', 'Frövi',
  'Fröslunda', 'Furuby', 'Furulund', 'Gallivare', 'Garphyttan',
  'Gassel', 'Gemla', 'Getinge', 'Gistad', 'Gislaved', 'Glimåkra',
  'Glommen', 'Gnosjö', 'Gottröra', 'Grabo', 'Grangarde', 'Grangesberg',
  'Granna', 'Grebbestad', 'Grisslehamn', 'Grums', 'Grundsund',
  'Gräsberg', 'Gräsmark', 'Gräddö', 'Gudmuntorp', 'Gullbrandstorp',
  'Gullspang', 'Gunnebo', 'Gunnilse', 'Gustafsberg', 'Gyllebo',
  'Gysinge', 'Hallabro', 'Hallefors', 'Hallsberg', 'Hallstahammar',
  'Hallstavik', 'Hamburgsund', 'Hammarö', 'Hammarby', 'Hammerdal',
  'Hamra', 'Hamrånge', 'Hanebo', 'Haparanda', 'Harbo', 'Harg',
  'Harplinge', 'Harriröd', 'Harryda', 'Havdhem', 'Heby',
  'Hedekas', 'Hedemora', 'Heden', 'Hedeskoga', 'Hedvig Eleonora',
  'Hennan', 'Herrljunga', 'Hillared', 'Hjärnarp', 'Hjärtsila',
  'Hjärup', 'Hjorted', 'Hjortkvarn', 'Hjuvik', 'Hofors',
  'Hoganas', 'Holmestrand', 'Holmsjo', 'Holmsund', 'Holmsveden',
  'Hovas', 'Hovmantorp', 'Hultafors', 'Hultsfred', 'Huskvarna',
  'Hyltebruk', 'Hyssna', 'Håbol', 'Håkantorp', 'Hällabrottet',
  'Hällbybrunn', 'Hällefors', 'Hälleforsnäs', 'Hällevadsholm',
  'Hällingsjö', 'Härnösand', 'Härryd', 'Härryda', 'Hässleby',
  'Hässlö', 'Hörby', 'Höganäs', 'Hökerum', 'Hörvik', 'Höstveda',
  'Iggesund', 'Immeln', 'Ingelstad', 'Insjön', 'Ingarö', 'Jakobsberg',
  'Järbo', 'Järeda', 'Järnforsen', 'Järpås', 'Jokkmokk', 'Julita',
  'Junsele', 'Järfälla', 'Järpen', 'Jönköping', 'Kagerod',
  'Kågeröd', 'Källby', 'Källstorp', 'Källunda', 'Karesuando',
  'Karleby', 'Karleviv', 'Karlholm', 'Karlsborg', 'Karlshamn',
  'Karlskoga', 'Karlskrona', 'Karlstad', 'Karungi', 'Katrineholm',
  'Kattarp', 'Kungsäter', 'Kjellerup', 'Klippan', 'Klockaretorpet',
  'Knivsta', 'Knutby', 'Kolbäck', 'Kolmården', 'Konga', 'Korsberga',
  'Kosta', 'Kramfors', 'Krokek', 'Krokom', 'Kungsbacka',
  'Kungshamn', 'Kungsör', 'Kungälv', 'Kungsängen', 'Kvibille',
  'Kvicksund', 'Kvikkjokk', 'Kvidinge', 'Kvismare', 'Kvistgård',
  'Kvännum', 'Kyrkhult', 'Köpingebro', 'Köpingsvik', 'Laholm',
  'Landsbro', 'Landvetter', 'Langasjo', 'Laxå', 'Lekeryd',
  'Leksand', 'Lerum', 'Liatorp', 'Lidköping', 'Lindberget',
  'Lindesberg', 'Lindome', 'Linköping', 'Ljungby', 'Ljungbyhed',
  'Ljungbyholm', 'Ljunghusen', 'Ljungsbro', 'Ljungskile', 'Ljusdal',
  'Ljusne', 'Locknevi', 'Lomma', 'Lorensberg', 'Lovene', 'Ludvika',
  'Lundsbrunn', 'Luspen', 'Lycke', 'Lyckeby', 'Lycksele', 'Lysekil',
  'Lönashult', 'Lönsboda', 'Löttorp', 'Löddeköpinge', 'Lövekulle',
  'Lövestad', 'Malax', 'Malmköping', 'Malmö', 'Malung', 'Mankarbo',
  'Mantorp', 'Margretetorp', 'Mariestad', 'Markaryd', 'Marstrand',
  'Matfors', 'Mellbystrand', 'Mellerud', 'Mjällby', 'Mjölby',
  'Mockfjärd', 'Molkom', 'Molle', 'Mora', 'Morjärv', 'Morkarlby',
  'Moskosel', 'Mullhyttan', 'Mullsjö', 'Munkedal', 'Munka-Ljungby',
  'Mölltorp', 'Mönsterås', 'Mörbylånga', 'Mörsil', 'Nacka',
  'Nässjö', 'Nattavaara', 'Nol', 'Norberg', 'Nordmaling',
  'Norrahammer', 'Norrala', 'Norralje', 'Norrsundet', 'Norsborg',
  'Norrtalje', 'Norrtälje', 'Norsholm', 'Nossebro', 'Nyhammar',
  'Nybro', 'Nyland', 'Nymölla', 'Nynas', 'Nynäshamn', 'Nässjö',
  'Odensbacken', 'Ödeshög', 'Öjebyn', 'Öjersjö', 'Ölanda',
  'Ölme', 'Ölsremma', 'Önneköp', 'Önnestad', 'Ör',
  'Örbyhus', 'Örebro', 'Örkelljunga', 'Örnsköldsvik', 'Örsted',
  'Örträsk', 'Össlöv', 'Österbybruk', 'Österbymo', 'Österhaninge',
  'Östersund', 'Österåker', 'Östhammar', 'Olofstrom', 'Olofström',
  'Ornas', 'Ornäs', 'Orsa', 'Orust', 'Oskarström', 'Oskarshamn',
  'Oxelösund', 'Pajala', 'Partille', 'Pellarne', 'Perstorp',
  'Piteå', 'Pixbo', 'Rå', 'Råå', 'Rådasjön', 'Ramsele',
  'Ransäter', 'Rantorp', 'Rättvik', 'Ravlanda', 'Rejmyre',
  'Rekarne', 'Rimbo', 'Ringkøbing', 'Rinkaby', 'Rockhammar',
  'Roja', 'Roma', 'Rombodal', 'Romelanda', 'Ronneby', 'Rosvik',
  'Rotebro', 'Rubblarp', 'Rudskoga', 'Runhällen', 'Rusksele',
  'Rydaholm', 'Rydbo', 'Rydsgård', 'Ryssa', 'Ränneslov',
  'Röbäck', 'Rölanda', 'Rönnang', 'Rönninge', 'Rörvik', 'Rött',
  'Sala', 'Salen', 'Sandared', 'Sandemar', 'Sandhem', 'Sandviken',
  'Sanne', 'Saro', 'Saröd', 'Saxdalen', 'Sikhall', 'Simlångsdalen',
  'Simsala', 'Simrishamn', 'Sjöbo', 'Sjömarken', 'Sjuntorp',
  'Skara', 'Skarblacka', 'Skarbygden', 'Skee', 'Skellefteå',
  'Skelleftehamn', 'Skene', 'Skillingaryd', 'Skinnskatteberg',
  'Skoghall', 'Skogstorp', 'Skoldinge', 'Skovde', 'Skruv',
  'Skultuna', 'Skurup', 'Skärblacka', 'Skärhamn', 'Skärholmen',
  'Skärplinge', 'Skövde', 'Smedjebacken', 'Smygehuk', 'Södertälje',
  'Solberg', 'Solberga', 'Sollefteå', 'Sollentuna', 'Solna',
  'Solvik', 'Sorbybruk', 'Sorsele', 'Spanga', 'Spekeröd',
  'Staffanstorp', 'Stenby', 'Stenberga', 'Stenby', 'Stenkvista',
  'Stenungsund', 'Stjärnhov', 'Stockaryd', 'Stockholm', 'Stockvik',
  'Stolpen', 'Stora Mellösa', 'Storuman', 'Strängnäs', 'Strömma',
  'Strömsberg', 'Strömsnäsbruk', 'Strömstad', 'Strömsund', 'Stugun',
  'Sundbyberg', 'Sundsvall', 'Sunnanå', 'Sunne', 'Surahammar',
  'Surte', 'Sveg', 'Svenstorp', 'Svenljunga', 'Svensbyn',
  'Svenshögen', 'Svinnegarnshed', 'Sysslebäck', 'Säffle', 'Sälen',
  'Säter', 'Sätila', 'Sävsjö', 'Söderala', 'Söderhamn', 'Söderköping',
  'Söderåkra', 'Södertälje', 'Sölvesborg', 'Sösdala', 'Tanumshede',
  'Täby', 'Täfteå', 'Tenhult', 'Tibro', 'Tidaholm', 'Tierp',
  'Timrå', 'Tingsryd', 'Tjörnarp', 'Tomelilla', 'Toreboda',
  'Torekov', 'Torsby', 'Torshälla', 'Torup', 'Tranås', 'Tranemo',
  'Trelleborg', 'Trollhättan', 'Trosa', 'Tullinge', 'Tumba',
  'Tunnelberga', 'Tylosand', 'Tyresö', 'Töcksfors', 'Töreboda',
  'Uddevalla', 'Ullared', 'Ulricehamn', 'Umeå', 'Ungsberg',
  'Upplands Väsby', 'Upplands-Bro', 'Uppsala', 'Urshult',
  'Vadstena', 'Valbo', 'Vallentuna', 'Vansbro', 'Vara', 'Varberg',
  'Vargön', 'Vaxholm', 'Vendelsö', 'Vetlanda', 'Vilhelmina',
  'Vimmerby', 'Vindeln', 'Visby', 'Vislanda', 'Vissefärda',
  'Vittsjö', 'Voxtorp', 'Vårgårda', 'Vänersborg', 'Väring',
  'Värnamo', 'Västervik', 'Västerås', 'Växjö', 'Värmdö',
  'Vätö', 'Ystad',
].filter((v, i, a) => a.indexOf(v) === i).sort();
